import { redirect } from "next/navigation";
import { ClassicShell } from "@/components/classic/ClassicShell";
import { Badge, Band, Card, Empty, LinkButton, Section } from "@/components/classic/pieces";
import { IconPlay } from "@/components/classic/icons";
import { getSession } from "@/lib/auth";
import { getWalletSummary } from "@/lib/financial/data";
import { piastresToPounds } from "@/lib/financial/money";
import { getNotifications } from "@/lib/notifications/data";
import { getLiveState, isValidHttpUrl } from "@/lib/community-live";
import { prisma } from "@/lib/prisma";
export const dynamic="force-dynamic";
type Row={id:string;teacherId:string;title:string;joinUrl:string;startsAt:Date;endsAt:Date;teacherName:string};
function money(p:number){return `${new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(piastresToPounds(p))} جنيه`;}
export default async function LivePage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){const s=await getSession();if(!s)redirect("/login?redirect_url=/live");const n=await getNotifications();const p=await searchParams;const balance=s.role==="student"?money((await getWalletSummary()).balancePiastres):"حساب مدرس";
 let sessions:Row[]=[];if(s.role==="teacher")sessions=await prisma.$queryRaw<Row[]>`SELECT l.*,COALESCE(tp."displayName",u.name) AS "teacherName" FROM "TeacherLiveSession" l JOIN "User" u ON u.id=l."teacherId" LEFT JOIN "TeacherProfile" tp ON tp."teacherId"=u.id WHERE l."teacherId"=${s.id} ORDER BY l."startsAt" DESC`;else{const subs=await prisma.teacherSubscription.findMany({where:{studentId:s.id,status:"active",OR:[{expiresAt:null},{expiresAt:{gt:new Date()}}]},select:{teacherId:true}});const ids=subs.map(x=>x.teacherId);if(ids.length)sessions=await prisma.$queryRaw<Row[]>`SELECT l.*,COALESCE(tp."displayName",u.name) AS "teacherName" FROM "TeacherLiveSession" l JOIN "User" u ON u.id=l."teacherId" LEFT JOIN "TeacherProfile" tp ON tp."teacherId"=u.id WHERE l."teacherId"=ANY(${ids}::text[]) ORDER BY l."startsAt" DESC`;}
 const now=new Date();return <ClassicShell title="مركز البث المباشر" balanceLabel={balance} unreadCount={n.unreadCount}>{p.error?<Band tone="danger" text={p.error}/>:null}{p.success?<Band tone="success" text={p.success}/>:null}{s.role==="teacher"?<Section title="انشر بثاً للمشتركين"><Card title="بيانات البث" icon={<IconPlay/>}><form method="post" action="/api/live" className="c-stack"><label className="c-field"><span>عنوان البث</span><input className="c-input" name="title" maxLength={140} required/></label><label className="c-field"><span>رابط البث (https)</span><input className="c-input" name="joinUrl" type="url" maxLength={1000} required/></label><label className="c-field"><span>موعد البداية</span><input className="c-input" name="startsAt" type="datetime-local" required/></label><label className="c-field"><span>موعد النهاية</span><input className="c-input" name="endsAt" type="datetime-local" required/></label><button className="c-btn c-btn--primary" type="submit">نشر البث للمشتركين</button></form></Card></Section>:null}<Section title={s.role==="teacher"?"جلساتك":"جلسات المدرسين المشترك معهم"}>{sessions.length?<div className="c-tiles">{sessions.map(x=>{const state=getLiveState(x.startsAt,x.endsAt,now);const label=state==="live"?"مباشر الآن":state==="upcoming"?"قادم":"انتهى";return <Card key={x.id} title={x.title} description={`${x.teacherName} · ${new Intl.DateTimeFormat("ar-EG",{dateStyle:"medium",timeStyle:"short"}).format(x.startsAt)}`} icon={<IconPlay/>} headerAction={<Badge label={label} tone={state==="live"?"green":state==="upcoming"?"blue":"neutral"}/>} footer={state==="live"&&isValidHttpUrl(x.joinUrl)?<LinkButton href={x.joinUrl} label="دخول البث الآن" external inline/>:undefined}/>})}</div>:<Card><Empty icon={<IconPlay/>} title="لا توجد جلسات بث" text={s.role==="teacher"?"انشر أول بث من النموذج بالأعلى.":"عندما ينشر مدرس مشترك معه رابط بث سيظهر هنا."}/></Card>}</Section></ClassicShell>}
